---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: k8s-topo
    namespace: default
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: k8s-topo-clusterrole
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    - pods
    - services
    verbs: ["*"]
  - apiGroups:
    - ""
    resources:
    - pods/exec
    verbs: ["*"]
  - apiGroups:
    - "networkop.co.uk"
    resources:
    - topologies
    verbs: ["*"]
  - apiGroups:
    - "networkop.co.uk"
    resources:
    - topologies/status
    verbs: ["*"]
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: k8s-topo-clusterrolebinding
  roleRef:
    kind: ClusterRole
    name: k8s-topo-clusterrole
    apiGroup: rbac.authorization.k8s.io
  subjects:
  - kind: ServiceAccount
    name: k8s-topo
    namespace: default
- apiVersion: v1
  kind: Service
  metadata:
    name: k8s-topo-service
    labels:
      run: k8s-topo-service
  spec:
    type: NodePort 
    ports:
    - port: 80
      nodePort: 30000
      protocol: TCP
    selector:
      app: k8s-topo
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: k8s-topo
    name: k8s-topo
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: k8s-topo
    template:
      metadata:
        labels:
          app: k8s-topo
      spec:
        serviceAccountName: k8s-topo
        hostNetwork: true
        containers:
        - image: networkop/k8s-topo:0.2.0
          imagePullPolicy: Always
          name: k8s-topo
          ports:
          - containerPort: 80